name: branvier_template
description: A new Branvier project.
version: 1.1.0

environment:
  sdk: ">=3.8.0 <4.0.0" # 3.32.0

dependencies:
  flutter:
    sdk: flutter
  
  #Core
  provide_it: ^0.19.0
  go_router: ^15.2.4

  #Http
  dio: ^5.8.0+1

  #Services
  tr_extension: ^0.9.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

  #Ui
  flutter_animate: ^4.5.2
  flutter_async: ^0.13.0
  formx: ^0.36.0

  #Utils
  package_info_plus: ^8.3.0
  logarte: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  branvier_lints: ^0.6.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
  
# dart pub global activate rps
scripts:
  test: flutter run -d chrome --wasm
  build: flutter build web --wasm --dart-define-from-file=lib/env.json

# For adding firebase https://firebase.flutter.dev/docs/overview, run:
# > dart pub add firebase_core, firebase_auth, cloud_firestore, cloud_functions, firebase_storage, firebase_analytics, firebase_crashlytics, firebase_messaging
# > firebase login
# > flutterfire configure

