name: branvier_template
description: A new Branvier project.
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Core
  provider: ^6.1.2
  go_router: ^13.2.0

  #Http
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

  #Services
  hive: ^2.2.3 #Storage
  flutter_secure_storage: ^9.0.0 #Crypto
  tr_extension: ^0.5.1 #Translation


  #Ui
  auto_injector: ^2.0.3
  flutter_animate: ^4.5.0
  flutter_async: ^0.7.1
  path_provider: ^2.1.2

  #Utils
  gap: ^3.0.1
  dartx: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  branvier_lints: ^0.1.18

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
  
