name: branvier_template
version: 0.1.0+1
publish_to: none
description: A new Branvier project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  branvier:
    git: https://github.com/Branvier/branvier.git
  flutter_modular: ^5.0.3
  flutter_hooks: ^0.18.6
  hive: ^2.2.3
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  google_fonts:
    git:
      url: https://github.com/material-foundation/google-fonts-flutter.git
      ref: proposal-awaitFontLoads
  i18n_extension: ^8.0.0
  mocktail: ^0.3.0
  # easy_localization: ^3.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/translations/