name: branvier_template
description: A new Branvier project
version: 1.3.0

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter

  # Core
  provide_it: ^0.22.0
  go_router: ^16.3.0
  go_transitions: ^0.8.2

  # Services
  dio: ^5.9.0
  shared_preferences: ^2.5.3

  # Utils
  tr_extension: ^0.9.2
  package_info_plus: ^9.0.0
  logarte: ^1.4.0

  # Ui
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2
  flutter_async: ^0.14.1
  formx: ^0.37.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  branvier_lints: ^0.7.1
  mocktail: ^1.0.4

# > flutter run -d chrome --wasm
# > flutter build web --wasm

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

# For adding firebase https://firebase.flutter.dev/docs/overview, run:
# > dart pub add firebase_core, firebase_auth, cloud_firestore, cloud_functions, firebase_storage, firebase_analytics, firebase_crashlytics, firebase_messaging
# > firebase login
# > flutterfire configure

