name: branvier_template
description: A new Branvier project.
version: 0.3.4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Core
  auto_injector: ^2.0.4
  provider: ^6.1.2
  go_router: ^14.1.4
  go_provider: ^1.5.0
  go_transitions: ^0.5.2

  #Http
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

  #Services
  hive: ^2.2.3 #Storage
  image_picker: ^1.1.1
  tr_extension: ^0.6.0 #Translation

  #Ui
  flutter_animate: ^4.5.0
  flutter_async: ^0.8.1
  path_provider: ^2.1.3
  formx: ^0.12.1
  gap: ^3.0.1

  #Utils
  dartx: ^1.2.0
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  branvier_lints: ^0.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
  
# dart pub global activate rps
scripts:
  test: flutter run -d chrome --release --dart-define-from-file=lib/env.json
  build: flutter build web --release --dart-define-from-file=lib/env.json