name: branvier_template
description: A new Branvier project.
version: 0.4.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Core
  auto_injector: ^2.0.5
  provider: ^6.1.2
  go_router: ^14.2.3
  go_provider: ^1.5.0
  go_transitions: ^0.6.0

  #Http
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

  #Services
  hive: ^2.2.3 #Storage
  image_picker: ^1.1.2
  tr_extension: ^0.6.1  #Translation

  #Ui
  flutter_animate: ^4.5.0
  flutter_async: ^0.10.1
  path_provider: ^2.1.4
  formx: ^0.17.1
  gap: ^3.0.1

  #Utils
  dartx: ^1.2.0
  package_info_plus: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  branvier_lints: ^0.3.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
  
# dart pub global activate rps
scripts:
  test: flutter run -d chrome --release --dart-define-from-file=lib/env.json
  build: flutter build web --release --dart-define-from-file=lib/env.json